version: '3.8'

services:

  # Log initialization for task workers (Deployed on Droplet #2)
  log-init:
    image: busybox
    volumes:
      - ./logs:/app/logs
    command: sh -c "mkdir -p /app/logs && chmod -R 777 /app/logs"
    restart: "no"

  # Scraping Workers (Deployed on Droplet #2)
  scraping-worker-0:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=0
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  scraping-worker-1:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=1
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  scraping-worker-2:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=2
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  scraping-worker-3:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=3
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always


  scraping-worker-4:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=4
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always


  scraping-worker-5:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=5
      - TOTAL_SCRAPING_WORKERS=${TOTAL_SCRAPING_WORKERS}
      - WORKER_TYPE=scraping
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  # OLD Analysis Workers - REPLACED BY DYNAMIC WORKERS ABOVE
  # analysis-worker-0:
  #   image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
  #   depends_on:
  #     - log-init
  #   volumes:
  #     - ./logs:/app/logs
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - PINECONE_API_KEY=${PINECONE_API_KEY}
  #     - RESEND_API_KEY=${RESEND_API_KEY}
  #     - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_REGION=${AWS_REGION}
  #     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  #     - GEMINI_API_KEY=${GEMINI_API_KEY}
  #     - TZ=Europe/Warsaw
  #     - WORKER_INDEX=0
  #     - TOTAL_ANALYSIS_WORKERS=${TOTAL_ANALYSIS_WORKERS}
  #     - WORKER_TYPE=analysis
  #     - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
  #     - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
  #   networks:
  #     - tasks_network
  #   restart: always

  # analysis-worker-5:
  #   image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
  #   depends_on:
  #     - log-init
  #   volumes:
  #     - ./logs:/app/logs
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - PINECONE_API_KEY=${PINECONE_API_KEY}
  #     - RESEND_API_KEY=${RESEND_API_KEY}
  #     - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_REGION=${AWS_REGION}
  #     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  #     - TZ=Europe/Warsaw
  #     - WORKER_INDEX=5
  #     - TOTAL_ANALYSIS_WORKERS=${TOTAL_ANALYSIS_WORKERS}
  #     - WORKER_TYPE=analysis
  #     - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
  #     - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
  #   networks:
  #     - tasks_network
  #   restart: always

  # Monitoring Worker (Deployed on Droplet #2)
  monitoring-worker-0:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=0
      - TOTAL_MONITORING_WORKERS=${TOTAL_MONITORING_WORKERS}
      - WORKER_TYPE=monitoring
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  # Cleanup Worker (Deployed on Droplet #2)
  cleanup-worker-0:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - log-init
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - WORKER_INDEX=0
      - TOTAL_CLEANUP_WORKERS=${TOTAL_CLEANUP_WORKERS}
      - WORKER_TYPE=cleanup
    networks:
      - tasks_network
    restart: always

  # Redis for Analysis Task Queue
  redis-analysis:
    image: redis:7-alpine
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - tasks_network
    restart: always

  # Dynamic Analysis Workers (Replace old analysis workers)
  analysis-worker-0:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_worker
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - WORKER_ID=analysis-0
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  analysis-worker-1:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_worker
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - WORKER_ID=analysis-1
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  analysis-worker-2:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_worker
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - WORKER_ID=analysis-2
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  analysis-worker-3:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_worker
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - WORKER_ID=analysis-3
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always

  analysis-worker-4:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_worker
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
      - /var/huggingface_cache:/app/.cache/huggingface
    environment:
      - WORKER_ID=analysis-4
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - TZ=Europe/Warsaw
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
    networks:
      - tasks_network
    restart: always


  # Analysis Task Producer (runs once daily via scheduler)
  analysis-task-producer:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    depends_on:
      - redis-analysis
      - log-init
    volumes:
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - ONEPLACE_EMAIL=${ONEPLACE_EMAIL}
      - ONEPLACE_PASSWORD=${ONEPLACE_PASSWORD}
      - TZ=Europe/Warsaw
      - WORKER_TYPE=analysis_producer
      - WORKER_INDEX=0
    networks:
      - tasks_network
    restart: always

  # Analysis Monitor (handles emails)
  analysis-monitor:
    image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
    command: python -m minerva.tasks.analyses.analysis_monitor
    depends_on:
      - redis-analysis
    volumes:
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis-analysis:6379/1
      - MONGODB_URI=${MONGODB_URI}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - TZ=Europe/Warsaw
    networks:
      - tasks_network
    restart: always

  # Tender Analysis Scheduler Workers (Deployed on Droplet #2)
  # tender-analysis-worker-0:
  #   image: ${REGISTRY}/${TASKS_IMAGE_NAME}:${GITHUB_SHA}
  #   depends_on:
  #     - log-init
  #   volumes:
  #     - ./logs:/app/logs
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - PINECONE_API_KEY=${PINECONE_API_KEY}
  #     - RESEND_API_KEY=${RESEND_API_KEY}
  #     - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_REGION=${AWS_REGION}
  #     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  #     - GEMINI_API_KEY=${GEMINI_API_KEY}
  #     - TZ=Europe/Warsaw
  #     - WORKER_INDEX=0
  #     - WORKER_TYPE=tender_analysis_schedudler
  #     - USER_ID=67c6cb742fee91862e135247
  #     - ANALYSIS_ID=680eb345e1189b4f5ce9dd32
  #   command: python -m minerva.tasks.tender_analysis_scheduler
  #   networks:
  #     - tasks_network
  #   restart: always


networks:
  tasks_network:
    driver: bridge